<a href="https://colab.research.google.com/github/spentapa3-lgtm/deeplearning-/blob/main/Long_Short_Term_Memory(LSTM)_Forward_Pass_with_Fixed_Weights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.set_printoptions(suppress=True)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)
def cross_entropy(y_true, y_pred):
    return -np.sum(y_true * np.log(y_pred + 1e-12))
Wf = np.array([[-0.3922, -0.0009, -0.0711, -0.6524, 0.1995],
              [ 0.723 ,  0.4047,  0.1089,  0.5632, -1.0513]])
bf = np.array([[-0.7044],
              [-0.5538]])
Wi = np.array([[ 0.2833, -0.1896,  0.7952,  0.9753,  0.1119],
              [-0.0299, -0.5395,  0.0708,  0.3999,  0.847 ]])
bi = np.array([[1.594],
              [1.48 ]])
Wo = np.array([[ 0.1023, -0.1504,  1.0928,  0.7877,  0.1063],
              [ 0.1616, -0.7025,  0.187 ,  0.9171,  0.715 ]])
bo = np.array([[1.8517],
              [1.6679]])
Wc = np.array([[-0.2761,  0.3366,  1.9493, -1.5433, -0.5777],
              [-0.6505, -0.4363, -0.7741, -1.3224,  1.6041]])
bc = np.array([[-0.1707],
              [-0.2208]])
Why = np.array([[-1.5545,  3.5032],
               [ 3.7474, -0.473 ],
               [-2.6135, -2.9926]])
by = np.array([[ 0.3001],
              [ 0.4803],
              [-0.7804]])
x1 = np.array([[1],[0],[0]])
x2 = np.array([[0],[1],[0]])
x3 = np.array([[0],[0],[1]])
inputs = [x1, x2, x3]
t1 = np.array([[0],[1],[0]])
t2 = np.array([[0],[0],[1]])
t3 = np.array([[1],[0],[0]])
targets = [t1, t2, t3]
hidden_size = 2
h = np.zeros((hidden_size,1))
c = np.zeros((hidden_size,1))
loss = 0
print("Predictions:\n")
for t in range(3):
    z = np.vstack((h, inputs[t]))
    f = sigmoid(Wf @ z + bf)
    i = sigmoid(Wi @ z + bi)
    o = sigmoid(Wo @ z + bo)
    c_tilde = np.tanh(Wc @ z + bc)
    c = f * c + i * c_tilde
    h = o * np.tanh(c)
    y = Why @ h + by
    p = softmax(y)
    loss += cross_entropy(targets[t], p)
    print(f"Time step {t+1} prediction:")
    print(np.round(p, 4))
    print()
print("Final Loss:", round(loss, 6))

Predictions:

Time step 1 prediction:
[[0.0036]
 [0.9827]
 [0.0137]]

Time step 2 prediction:
[[0.0086]
 [0.0096]
 [0.9817]]

Time step 3 prediction:
[[0.9861]
 [0.0032]
 [0.0107]]

Final Loss: 0.049908
